### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by nrc** [mozilla/dxr#218]
We currently just have syntax highlighting and dumb search for Rust. Would be good to have full support.

See https://github.com/nick29581/dxr/tree/rust and https://github.com/nick29581/rust/tree/dxr for progress.

**Comment by nick29581** [comment]
I'm now tracking DXR/Rust implementation in its own repo, since there is quite a lot of overlap with Rust stuff - see https://github.com/nick29581/rust-dxr

**Comment by erikrose** [comment]
Thanks for letting me know!

**Comment by nrc** [comment]
This is landed and working now: https://dxr.mozilla.org/rust/source/

If you find issues: https://github.com/nick29581/rust-dxr
