### ISSUE TITLE
Permanent i.e. explicit-revision links

### ISSUE THREAD

**Issue by bjacob** [mozilla/dxr#273]
I would like very much the ability to get permanent DXR links, i.e. DXR links to a specific revision of the source code.

I need that to be able to paste DXR links in bugs. At the moment, I have to go back to hg.mozilla.org for that.

Note: this was raised in the "Poll: What do you need in MXR/DXR?" thread on dev-platform, and +1'd by someone else.

Apologies if this feature already exists and I didn't find it.

**Comment by srenatus** [comment]
:+1: Is this possible right now?

**Comment by erikrose** [comment]
It is on staging: https://dxr.allizom.org. We're working on putting that into production right now.
