### ISSUE TITLE
Index XPIDL

### ISSUE THREAD

**Issue by indygreg** [mozilla/dxr#281]
It would be rad if DXR could index XPIDL. MXR does this already.

The canonical code for parsing XPIDL files lives at https://hg.mozilla.org/mozilla-central/file/668f29cd71b3/xpcom/idl-parser/xpidl.py. See high-level usage at https://hg.mozilla.org/mozilla-central/file/668f29cd71b3/python/mozbuild/mozbuild/action/xpidl-process.py#l27.

Initially, basic support is all that is needed. But it would be really cool if DXR could perform interface inheritance and dump full API details for a given interface, including relationship graphs.

**Comment by pelmers** [comment]
Hi, I've been using [bug 1109804](https://bugzilla.mozilla.org/show_bug.cgi?id=1109804) to track this issue.
PR #456 implements indexing XPIDL files; you can find a description of what it does in [this docstring](https://github.com/pelmers/dxr/blob/742a6d9bd407a35907fa60a7efea458eb316b179/dxr/plugins/xpidl/__init__.py#L1-L11).

**Comment by glasserc** [comment]
Is this still open? #456 seems to have gotten merged a while ago.

**Comment by pelmers** [comment]
yes, closing
