### ISSUE TITLE
Highlight .idl files as c++

### ISSUE THREAD

**Issue by mystor** [mozilla/dxr#420]
I imagine that this could be done with a similar hack to the parsing .h files as .cpp, Most of the time .idl looks pretty good as c++ (in fact, in many mozilla files, emacs is told to use c++-mode for .idl files).

**Comment by erikrose** [comment]
Good idea! Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1168878. (I'm trying to phase out the GH issue tracker.)
