### ISSUE TITLE
offset param in url

### ISSUE THREAD

**Issue by jespersh** [mozilla/dxr#469]
1. Visit https://dxr.mozilla.org/ (should redirect to https://dxr.mozilla.org/mozilla-central/source/)
2. Press the page somewhere so the input box doesn't have focus.
3. Press End and Home repeatedly
4. Enjoy watching offset increase

Reached https://dxr.mozilla.org/mozilla-central/source/?offset=6000 before I was entertained enough.

**Comment by jespersh** [comment]
No longer seems to be an issue. dxr code might have changed

**Comment by erikrose** [comment]
Thanks for letting us know!

**Comment by jespersh** [comment]
For the record it appears it was fixed in https://github.com/mozilla/dxr/commit/85f6f796b42a4eb2f025195c2c4d55213d7ff727
