### ISSUE TITLE
[UI] dxr should report "freshness" information of data per tree

### ISSUE THREAD

**Issue by hwine** [mozilla/dxr#523]
DXR output has a page footer which expresses the version and freshness of the code base. It needs the same for the search data. See, e.g. https://bugzil.la/1262295 where the data is old, but nothing alerts the user to that condition.

Here's a sample display from the [Mozilla installation](https://dxr.mozilla.org/build-central/search?q=release_channel_mapping) showing the situation:
![screen shot 2016-04-05 at 19 49 25](https://cloud.githubusercontent.com/assets/132412/14304437/8d65590a-fb67-11e5-998a-5aa2e34d7f9d.png)

**Comment by klibby** [comment]
Just had a query from #releng, to ask if it was possible to determine which rev a given index is from. The index date at the bottom was a 'close enough' answer, but it would be nice if the rev were more obvious/easier to see.

**Comment by erikrose** [comment]
* Show hash: https://bugzilla.mozilla.org/show_bug.cgi?id=938222
* Warn when old: https://bugzilla.mozilla.org/show_bug.cgi?id=1289478

Thanks for filing, Hal.
