### ISSUE TITLE
RFC: Incremental build support.

### ISSUE THREAD

**Issue by caugner** [mozilla/dxr#586]
Are there any plans to support incremental builds?
I saw that PR #121 had a go at this, but hasn't been finished and had kind of a limited scope.

_Incremental builds_ have two major advantages:
1. The **index is always up to date**.
2. **Indexing is much faster**, as only changes need to be re-indexed or removed from the index.

My approach would be to delegate this to the version control systems, e.g.

``` python
# vcs.py

class Vcs(object):

    # Either …

    @classmethod
    def get_tracked_files(cls, path):
        """Return dict of tracked files with their respective revision."""
        return NotImplemented

    # … or …

    @classmethod
    def get_changed_files(cls, path, base_rev, head_rev):
        """Return list of changed files between base_rev (excl.) and head_rev (incl)."""
        return NotImplemented

```

By comparing the index with the list of tracked or changed files respectively, DXR could determine which files have been added, modified or deleted.

Having said this, the `get_tracked_files` option is probably more robust as it's agnostic to revisions, while we would need something like `Vcs.get_current_revision(cls, path)` to properly utilise the `get_changed_files` option.

P.S.: If we then add `Vcs.update(cls, path)`, we could go further and automate the whole process:

``` bash
# Index files, start the server and keep both the repositories and the index up to date.
./dxr run
```

**Comment by caugner** [comment]
I wasn't aware of this, because I'm planning on using DXR in a Java project with only `pygmentize` activated. I would say two things though:

1. Without any plugins, the incremental build should work as described.
2. Plugins like `clang` that add indexing dependencies between files could/should keep track of these dependencies themselves or signal that they don't support incremental builds.

**Comment by erikrose** [comment]
Sounds worth at least trying to come up with a design. Feel free!

Let me also throw another use case on the fire: some very large repos (like our 500GB-scale add-ons repo) aren't under VCS control but rather are stitched together out of a pile of rsyncs. In these cases, the mod dates on disk would be where to look for changes.
