### ISSUE TITLE
Camel-case search.

### ISSUE THREAD

**Issue by caugner** [mozilla/dxr#587]
Eclipse and possibly other IDEs have a handy featured called _camel-case search_. This means that one can find a file, a class or a method by combining prefixes of camel-case name parts.

For example, the term `NullPointerException` consists of the parts `Null`, `Pointer` and `Exception`. Therefore it can be found among others via the abbreviated search terms _NPE_, _NuP_, _NPoi_ and _NPEx_.

This has two advantages:
1. It's faster, as one has to type less.
2. It's convenient, if one doesn't know the exact name (e.g. _NullPointerException_ vs. _NullPointingError_).

In general, DXR supports sophisticated queries like these using the `regexp` operator.
However, typing out the corresponding query `regexp:N[a-z]*P[a-z]*E` not only yields a warning (_Regexes need at least 3 literal characters in a row for speed._), but it also foils the "type less" advantage:

```
NullPointerException
regexp:N[a-z]*P[a-z]*E
```

It would be handy if camel-case search would be supported as follows:
1. with a new `cc` operator to match content,
2. without any operator to match filenames,
3. in structural operators (such as `id`, `type`, `method`).

**Comment by erikrose** [comment]
There's a lot of UI design thought that needs to go into something like this. But I don't think it's impossible. Specifically, we might be able to present such results separately from the main body of (exact) results as https://github.com/mozilla/dxr/pull/541 does. (And I'd kind of like to move those from the right sidebar to above the exact results.) I think we should wait for #541 to land and then mock up what this might look like.

**Comment by erikrose** [comment]
(Btw, I am a big fan of camel-case search in my workflow: I run my whole life with LaunchBar.)
