### ISSUE TITLE
RFC: Keyboard support.

### ISSUE THREAD

**Issue by caugner** [mozilla/dxr#588]
Developer productivity could be significantly increased by adding support for keyboard control.
### Operators

**Keyboard shortcuts for the operators** allow users to focus on the search terms rather than on the syntax:
- ext: <kbd>Ctrl</kbd> + <kbd>E</kbd>
- file <kbd>Ctrl</kbd> + <kbd>F</kbd>
- path: <kbd>Ctrl</kbd> + <kbd>P</kbd>
- regexp: <kbd>Ctrl</kbd> + <kbd>R</kbd>

If we are concerned about browser shortcuts (i.e. <kbd>F</kbd> Find, <kbd>P</kbD> Print, <kbd>R</kbd> Refresh), we could limit them to search field focus and/or use <kbd>Ctrl</kbd> + <kbd>Shift</kbd> instead of just <kbd>Ctrl</kbd>.
### Search Results

**Keyboard navigation in the search results** allow users to faster navigate to a match.
- Previous file: <kbd>Ctrl</kbd> + <kbd>Up</kbd>
- Previous match: <kbd>Up</kbd>
- Open file/match: <kbd>Return</kbd>
- Next match: <kbd>Down</kbd>
- Next file: <kbd>Ctrl</kbd> + <kbd>Down</kbd>

In case the search results don't include the desired match, we could easily go back to the search field (with a cursor at its end): <kbd>Ctrl</kbd> + <kbd>Q</kbd>
### File view

**Keyboard control in the file view** allows more smoothier selection of lines:
- Goto line: <kbd>Ctrl</kbd> + <kbd>G</kbd>
- Go to previous line: <kbd>Up</kbd>
- Go to next line: <kbd>Down</kbd>
- Add current line to selection: <kbd>Ctrl</kbd> + <kbd>Space</kbd>
- Goto and add previous line to selection (and current line, if not yet selected): <kbd>Shift</kbd> + <kbd>Up</kbd>
- Goto and add next line to selection (and current line, if not yet selected): <kbd>Shift</kbd> + <kbd>Down</kbd>
- Replace selection with current line: <kbd>Space</kbd>
### VCS links

**Keyboard shortcuts for the VCS links** could facilitate access to these:
- Open permalink (*): <kbd>Ctrl</kbd> + <kbd>P</kbd>
- Open blame: <kbd>Ctrl</kbd> + <kbd>B</kbd>
- Open diff: <kbd>Ctrl</kbd> + <kbd>D</kbd>
- Open log: <kbd>Ctrl</kbd> + <kbd>L</kbd>

(*) = Or better: Show readonly textfield with permalink inside (cf. GitHub clone URL field).

**Comment by erikrose** [comment]
1. Overall, keyboard accessibility is a fine idea.
2. We'll definitely have to dodge OS-native shortcut keys. Ctrl+shift is fine.
3. I like the idea of being able to move from result to result with the keyboard, but I also personally tend to use uparrow and downarrow to scroll the viewport. Any ideas for dealing with people like me? I wonder what would happen if we made the results Tab-able.
4. In general, how could we make the keyboard shortcuts discoverable?
5. There's an HTML5 clipboard API we could use now to add Copy buttons to things like the permalink and the navigation breadcrumbs.

**Comment by caugner** [comment]
Ad 3.: In general, it would be ideal if the user doesn't need to scroll the viewport at all. Until then, we could either dodge these shortcut keys and combine the arrow keys with <kbd>Ctrl</kbd> and/or <kbd>Ctrl</kbd> + <kbd>Shift</kbd> or we provide a shortcut to toggle keyboard shortcuts. In addition, we could allow jumping to a specific result item, for which we would need to number them in an elegant, non distracting way; then <kbd>Tab</kbd> (to leave search input field) and <kbd>1</kbd> <kbd>5</kbd> <kbd>Return</kbd> would suffice to open result number 15, for instance.

Ad 4.: We could add a hint behind "N results from the X tree:" and a Keyboard symbol next to the "?" symbol, which could open a dialog similar to the "Operators" dialog with all the keyboard shortcuts.

**Comment by erikrose** [comment]
3. The user may always want to scroll the viewport for reasons of his own, even if we provide a "better" alternative. We should endeavor not to break accustomed behavior. I like the dodging more than the shortcut-to-enable-shortcuts. In UI design, I consider modes something to typically be avoided.

4. A keyboard symbol isn't a bad idea. Or we can just make them part of the ? orb.
