### ISSUE TITLE
DXR should be discoverable by Firefox as a search provider

### ISSUE THREAD

**Issue by na-g** [mozilla/dxr#618]
I am unable to add DXR as a search provider to in Firefox from the search bar while visiting a DXR incidences, either my own or https://dxr.mozilla.org/mozilla-central/source/ .

**Comment by pelmers** [comment]
Hi, is this duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=813521?
Last comment is about adding an OpenSearch xml to the site.

**Comment by na-g** [comment]
@pelmers, is bugzilla the primary tracker for the project?

**Comment by pelmers** [comment]
yep!

**Comment by erikrose** [comment]
On my Long List of things to do is to close the GH tracker. If anybody wants to help port bugs over to bugzilla, that'd be a welcome help! :-)
