### ISSUE TITLE
How to add a new setting in dxr.config

### ISSUE THREAD

**Issue by AlexPham1988** [mozilla/dxr#627]
If I want to add a new setting , what should I do ?

[code]
source_folder       =  <my_source_code_dir> 
build_command   =
**my_setting           = value**

I tried and receive dxr.exceptions.ConfigError while indexing

Thank you and happy new year

Alex

**Comment by erikrose** [comment]
The trick is that you need to declare your new setting in config.py. Validation rules are specified using the https://pypi.python.org/pypi/schema/ library. Let me know if you need further help!
