### ISSUE TITLE
Clang plugin support for 3.9.1 ?

### ISSUE THREAD

**Issue by AlexPham1988** [mozilla/dxr#630]
Hi

Currently clang plugin only compatible with clang++ 3.5 . I run clang++ 3.9 command along with libclang-index-plugin.so ,  but it did not generate *.csv file.

I switched to clang++ 3.5 --> It worked well

Please consider to upgrade clang plugin code to make it work with 3.9.1.

Thank you

Alex

**Comment by erikrose** [comment]
If you look at the set_up_ubuntu.sh script that sets up the docker image, you'll see that we support at least clang 3.8. 3.9 support would be a great contribution; it likely requires only some CLANG_AT_LEAST additions in dxr-index.cpp, if you'd like to have a try.

**Comment by AlexPham1988** [comment]
Hi Erik
For example , this condition:

#if CLANG_AT_LEAST(3, 5)
      recordValue("type", d->getCallResultType().getAsString(printPolicy));
#else
      recordValue("type", d->getResultType().getAsString(printPolicy));
#endif

Say, if I change to CLANG_AT_LEAST(3, 9) , it would compile the same code with3.5 right ? Similarly with other CLANG_AT_LEAST(3, 7) conditions. There are totally 16 CLANG_AT_LEAST conditions, I reviewed one by one and remove all the unnecessary code . For example:

  #if CLANG_AT_LEAST(3, 7)
    void Defined(const Token &tok, const MacroDefinition &md,
                 SourceRange range) override;
  #elif CLANG_AT_LEAST(3, 4)
    void Defined(const Token &tok, const MacroDirective *md,
                 SourceRange range) override;
  #else
    void Defined(const Token &tok, const MacroDirective *md) override;
  #endif

would become only:

void Defined(const Token &tok, const MacroDefinition &md,
                 SourceRange range) override; // -->Only condition 3.7 

But the plugin still did not work with clang3.9 . I also add some "count" to print out some debug message but they did not show up.

I think we should reconsider how clang3.9 plugin works , and modify accordingly. May be something has changed in clang3.9

**Comment by erikrose** [comment]
You shouldn't need to remove any code; that old stuff still usefully enables DXR to work with old clangs and doesn't hurt anything. But clang has the habit of changing its API in small ways with every point release: that's what the #ifs are for. So your task, should you choose to accept it, is to re-express the changed calls for the new API and wrap them in CLANG_AT_LEAST(3, 9) conditionals.

**Comment by AlexPham1988** [comment]
So that mean it not simply change CLANG_AT_LEAST , but require some changes in how to call the clang 3.9 API.
By the way, I feel kind of awkward to ask this :) :  libclang-index-plugin.so should be generated by clang, not gcc  ?

Thank you

**Comment by erikrose** [comment]
> So that mean it not simply change CLANG_AT_LEAST , but require some changes in how to call 
> the clang 3.9 API.

Correct.

> By the way, I feel kind of awkward to ask this :) : libclang-index-plugin.so should be generated by clang, not gcc ?

It shouldn't matter. The makefile references the compiler as `$(CXX)`, and it also calls `which clang`, so clearly the intent is to use clang. It may not be so on our Docker image, though.

**Comment by AlexPham1988** [comment]
I not sure it is the best , decent-est way but replace all CLANG_AT_LEAST(3, 7) with CLANG_AT_LEAST(3, 9) should work

Thank you for your consider

**Comment by erikrose** [comment]
That change shouldn't do anything, since anything >= 3.7 is already >= 3.9.
