### ISSUE TITLE
Cannot access https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/debugger.js

### ISSUE THREAD

**Issue by ddragana** [mozilla/dxr#646]
I tried to access https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/debugger.js but it doe not work.

From firefox log, I seen that tls handshakes finishes and firefox sends request , after some time the connection gets a tls allert.

**Comment by ddragana** [comment]
https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/new/

any many other that I have look at worked just normal.

**Comment by ExE-Boss** [comment]
At the time you opened this, it’s likely that DXR hadn’t yet had the latest `mozilla‑central` sources pushed to it, as it works now, but I get a 404 from https://dxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/videocontrols.js, which was added in [~~bug 1431255~~](https://bugzil.la/1431255 "Provide a way to create a 'UA' shadow root / slots that are not accessible to the page").

**Comment by erikrose** [comment]
DXR's build of moz-central should be up to date now.
