### ISSUE TITLE
Question: atomicity/consistency of incremental indexing

### ISSUE THREAD

**Issue by mbautin** [mozilla/dxr#683]
Suppose I have a code repository and I continuously pull from it and run a DXR indexing job every time new commits appear. Would the index always reflect a consistent state as of the latest completed indexing job as of a particular commit, or is it sometimes possible (through the web UI) to observe an inconsistent state, when only a subset of files / symbols from the most recent commit have been inserted into the index? E.g. is it ever possible to observe symbol references/occurrences being inconsistent with the actual source file stored in Elasticsearch, if the former have been updated as of the new commit, and the latter is still as of the old commit, or vice versa?

**Comment by erikrose** [comment]
It should never be possible to observe an inconsistent whole. We index to a fresh ES index and then, at the end, atomically swap it, using aliases, with the old index.
