### ISSUE TITLE
missed keys set(['python', 'buglink', 'xpidl'])

### ISSUE THREAD

**Issue by Headline** [mozilla/dxr#696]
Hello; I am having issues getting dxr to index. Following the documentation I've gotten this far, but following the example `dxr.config` script shows errors that I'm missing some fields. Perhaps the documentation needs to be tweaked or I'm doing something incorrectly. Any help would be greatly appreciated, thanks!

```
[DXR]
# Some global options here, if you like

[sourcemod]
source_folder       = /home/dxr/sourcemod
build_command       = mkdir build; cd build; python3 ../configure.py --enable-optimize --sdks=episode1,css,tf2,l4d2,csgo,dota; ambuild
```

![Screenshot from 2020-03-29 07-26-58](https://user-images.githubusercontent.com/11095737/77851839-116ff280-7190-11ea-8398-fdb1fef2d6a6.png)

**Comment by abbeyj** [comment]
These are plugins that have required configuration.  The docs should probably be updated but unfortunately there is no active development being done on DXR at the moment.

If you don't need these plugins then you can disable them and they will no longer complain:

```
[DXR]
disabled_plugins=buglink python xpidl
```

Alternatively you can add the required configuration for one or more of these plugins if you'd like to use them.  See the `dxr/plugins` directory for the code behind each one of these plugins (`dxr/plugins/buglink`, `dxr/plugins/python`, `dxr/plugins/xpidl`).  Look for `config_schema` in the corresponding `__init__.py` file for the allowed keys.  There are example configuration files in the `dxr.config` files under the `tests` subdirectories (`dxr/plugins/buglink/*/dxr.config`, `dxr/plugins/python/tests/*/dxr.config`, `dxr/plugins/xpidl/tests/*/dxr.config`).

If you wanted just the buglink plugin and not the other two you could use something like:

```
[DXR]
disabled_plugins = python xpidl

[sourcemod]
# your keys here
    [[buglink]]
    name = Your Bug Tracker
    url = http://bugs.example.com/%s
    # you can also use a regex key here
```

**Comment by Headline** [comment]
Very helpful response thank you!
