### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by smuzaffar** [mozilla/dxr#704]
Looks like currently dxr only support python2 ( as I see many python2 style `print` statements). Are there any plans to support python3?

**Comment by donno** [comment]
Mozilla have been moving away from DXR to SearchFox. A banner was added to mention it was being decommissioned (ef09324a32930e2769e6ff63eaa8de76fcf79ee3).

>" It's not actively maintained anymore" - erikrose
   [Source](https://github.com/mozilla/dxr/issues/697#issuecomment-664571975) 

So Python3 seems unlikely, unless there is a new maintainer comes on board and/or the community picks it up.

**Comment by erikrose** [comment]
That said, it'd be an easy port. All of its important dependencies support 3. Feel free to have at it!
